name: astrocalc
description: A library for calculating sun and moon positions and phases.
version: 0.0.1
homepage: https://pub.dartlang.org/packages/astrocalc
author: PJ Essien <princess-jewel.essien@andela.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
