name: astrocalc
description: A library for calculating sun and moon positions and phases.
version: 0.0.1
homepage: https://github.com/andela-pessien/astrocalc
author: PJ Essien <princess-jewel.essien@andela.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
